kind: pipeline
name: default

steps:
- name: build
  image: python:3
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - pip install poetry
  - poetry install
  - poetry run pyinstaller cli.py --onefile
  - cp dist/cli /tmp/cache/devtool-$DRONE_TAG

- name: run 
  image: python:3
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - chmod +x /tmp/cache/devtool-$DRONE_TAG
  - /tmp/cache/devtool-$DRONE_TAG --help

- name: publish
  image: plugins/github-release
  volumes:
  - name: cache
    path: /tmp/cache
  settings:
    title: $DRONE_TAG
    files: /tmp/cache/devtool-$DRONE_TAG
    api_key:
      from_secret: gh_token

trigger:
  event:
  - tag

volumes:
- name: cache
  temp: {}
