kind: pipeline
name: default

steps:
- name: build
  image: python:3
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - pip install poetry
  - poetry install
  - poetry run pyinstaller cli.py --onefile
  - ls dist/
  - ls /tmp



volumes:
- name: cache
  temp: {}
