image: python:3

stages:
- build


build:linux:
  stage: build
  before_script:
  - pip install poetry
  script:
  - poetry install
  - poetry run pyinstaller devtool/devtool.py --onefile
  artifacts:
    name: linux
    paths:
    - dist/devtool
    expire_in: 30 days

build:mac:
  tags:
  - osx
  stage: build
  before_script
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install poetry
  script:
  - poetry install
  - poetry run pyinstaller devtool/devtool.py --onefile
  artifacts:
    name: osx
    paths:
    - dist/devtool
    expire_in: 30 days
