image: python:3

stages:
- build


build:
  stage: build
  before_script:
  - pip install poetry
  script:
  - poetry install
  - poetry run pyinstaller devtool/devtool.py --onefile
  artifacts:
    paths:
    - dist/devtool
    expire_in: 30 days