image: python:3

stages:
- build
- release


build:linux:
  stage: build
  before_script:
  - pip install poetry
  script:
  - poetry install
  - poetry run pyinstaller cli.py --onefile
  artifacts:
    name: linux
    paths:
    - dist/cli
    expire_in: 2hr

build:mac:
  tags:
  - osx
  stage: build
  before_script:
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install poetry
  script:
  - poetry install
  - poetry run pyinstaller cli.py --onefile
  artifacts:
    name: osx
    paths:
    - dist/cli
    expire_in: 2hr

release:mac:
  tags:
  - osx
  stage: release
  only:
  - tags
  before_script:
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install gitlab-release
  script:
  - cp dist/cli dist/devtool-$CI_COMMIT_TAG-OSX
  - python -m gitlab_release $PRIVATE_TOKEN dist/devtool-$CI_COMMIT_TAG-OSX
  dependencies:
    - build:mac

release:linux:
  stage: release
  only:
    - tags
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install gitlab-release
  script:
    - cp dist/cli dist/devtool-$CI_COMMIT_TAG-linux
    - python -m gitlab_release $PRIVATE_TOKEN dist/devtool-$CI_COMMIT_TAG-linux
  dependencies:
    - build:linux
